import codecs

content = """import 'package:flutter/material.dart';

final ValueNotifier<String> globalLanguage = ValueNotifier('EN (US)');

const Map<String, Map<String, String>> dictionary = {
  'EN (US)': {
    'home': 'Home',
    'cart': 'Cart',
    'favorite': 'Favorite',
    'profile': 'Profile',
    'search_hint': 'Search clothes, collections...',
    'popular_deals': 'Popular Deals',
    'see_all': 'See All',
    'new_arrivals': 'New Arrivals',
    'categories': 'Categories',
    'my_orders': 'My Orders',
    'settings': 'Settings',
    'notifications': 'Notifications',
    'help_support': 'Help & Support',
    'logout': 'Logout',
    'checkout': 'Checkout',
    'subtotal': 'Subtotal',
    'shipping': 'Shipping',
    'place_order': 'Place Order',
    'add_to_cart': 'Add to Cart',
    'buy_now': 'Buy Now',
    'size': 'Size',
    'color': 'Color',
    'description': 'Description',
    'reviews': 'Reviews',
    'filter': 'Filter',
    'apply_filter': 'Apply Filter',
    'price_range': 'Price Range',
    'clear_all': 'Clear All',
    'shopping_cart': 'Shopping Cart',
    'wishlist': 'Wishlist',
    'empty_cart': 'Your cart is empty',
    'empty_wishlist': 'Your wishlist is empty',
    'add_all_to_cart': 'Add All to Cart',
    'my_cart': 'My Cart',
    'total': 'Total:',
    'start_shopping': 'Start Shopping',
    'your_cart_is_empty': 'Your Cart is Empty',
    'hot': 'Hot',
    'favorites': 'Favorites',
    'saved_items': 'saved items',
    'all_items_in_stock': 'All items in stock',
    'move_all_to_cart': 'Move All to Cart',
    'no_items_to_move': 'No items to move',
    'moved_all_to_cart': 'Moved all to Cart!',
    'account_profile': 'Account & Profile',
    'orders': 'Orders',
    'vouchers': 'Vouchers',
    'personal_info': 'Personal Info',
    'personal_info_desc': 'Name, Email, Phone number',
    'my_orders_desc': 'Order history & tracking',
    'promos_alerts': 'Promos & status alerts',
    'payment_methods': 'Payment Methods',
    'payment_methods_desc': 'Visa ending in 4242',
    'faq_desc': 'FAQ & Customer Service',
    'sign_out_desc': 'Sign out of your account',
    'pending': 'Pending',
    'track': 'Track',
    'details': 'Details',
    'no_orders_yet': 'No orders yet.',
    'main_collections': 'MAIN COLLECTIONS',
    'choose_a_category': 'Choose a Category',
    'popular_caps': 'POPULAR',
    'items_count': ' items',
    'top_customer_review': 'TOP CUSTOMER REVIEW',
    'verified_buyer': 'Verified Buyer',
    'description_caps': 'DESCRIPTION',
    'size_guide': 'Size Guide',
    'select_size': 'SELECT SIZE',
    'quantity': 'Quantity',
    'default': 'Default',
  },
  'ID (ID)': {
    'home': 'Beranda',
    'cart': 'Keranjang',
    'favorite': 'Favorit',
    'profile': 'Profil',
    'search_hint': 'Cari pakaian, koleksi...',
    'popular_deals': 'Promo Populer',
    'see_all': 'Lihat Semua',
    'new_arrivals': 'Produk Baru',
    'categories': 'Kategori',
    'my_orders': 'Pesanan Saya',
    'settings': 'Pengaturan',
    'notifications': 'Notifikasi',
    'help_support': 'Bantuan & Dukungan',
    'logout': 'Keluar',
    'checkout': 'Pembayaran',
    'subtotal': 'Subtotal',
    'shipping': 'Pengiriman',
    'place_order': 'Buat Pesanan',
    'add_to_cart': 'Ke Keranjang',
    'buy_now': 'Beli Sekarang',
    'size': 'Ukuran',
    'color': 'Warna',
    'description': 'Deskripsi',
    'reviews': 'Ulasan',
    'filter': 'Penyaring',
    'apply_filter': 'Terapkan Filter',
    'price_range': 'Rentang Harga',
    'clear_all': 'Hapus Semua',
    'shopping_cart': 'Keranjang Belanja',
    'wishlist': 'Daftar Keinginan',
    'empty_cart': 'Keranjang Anda kosong',
    'empty_wishlist': 'Wishlist Anda kosong',
    'add_all_to_cart': 'Masukkan Semua',
    'my_cart': 'Keranjang Saya',
    'total': 'Total:',
    'start_shopping': 'Mulai Belanja',
    'your_cart_is_empty': 'Keranjang Kosong',
    'hot': 'Populer',
    'favorites': 'Favorit',
    'saved_items': 'disimpan',
    'all_items_in_stock': 'Semua tersedia',
    'move_all_to_cart': 'Pindah ke Keranjang',
    'no_items_to_move': 'Tidak ada',
    'moved_all_to_cart': 'Berhasil dipindah!',
    'account_profile': 'Akun & Profil',
    'orders': 'Pesanan',
    'vouchers': 'Voucher',
    'personal_info': 'Info Pribadi',
    'personal_info_desc': 'Nama, Email, No HP',
    'my_orders_desc': 'Riwayat pesanan',
    'promos_alerts': 'Promo & notifikasi',
    'payment_methods': 'Metode Pembayaran',
    'payment_methods_desc': 'Visa berakhiran 4242',
    'faq_desc': 'FAQ & Bantuan',
    'sign_out_desc': 'Keluar dari akun',
    'pending': 'Menunggu',
    'track': 'Lacak',
    'details': 'Detail',
    'no_orders_yet': 'Belum ada pesanan.',
    'main_collections': 'KOLEKSI UTAMA',
    'choose_a_category': 'Pilih Kategori',
    'popular_caps': 'POPULER',
    'items_count': ' barang',
    'top_customer_review': 'ULASAN TERBAIK',
    'verified_buyer': 'Pembeli Terverifikasi',
    'description_caps': 'DESKRIPSI',
    'size_guide': 'Panduan Ukuran',
    'select_size': 'PILIH UKURAN',
    'quantity': 'Kuantitas',
    'default': 'Bawaan',
  },
  'ES (ES)': {
    'home': 'Inicio',
    'cart': 'Carrito',
    'favorite': 'Favorito',
    'profile': 'Perfil',
    'search_hint': 'Buscar ropa, colecciones...',
    'popular_deals': 'Ofertas Populares',
    'see_all': 'Ver Todo',
    'new_arrivals': 'Nuevas Llegadas',
    'categories': 'Categorías',
    'my_orders': 'Mis Pedidos',
    'settings': 'Configuración',
    'notifications': 'Notificaciones',
    'help_support': 'Ayuda y Soporte',
    'logout': 'Cerrar Sesión',
    'checkout': 'Pagar',
    'subtotal': 'Subtotal',
    'shipping': 'Envío',
    'place_order': 'Hacer Pedido',
    'add_to_cart': 'Al Carrito',
    'buy_now': 'Comprar Ahora',
    'size': 'Tamaño',
    'color': 'Color',
    'description': 'Descripción',
    'reviews': 'Reseñas',
    'filter': 'Filtrar',
    'apply_filter': 'Aplicar Filtro',
    'price_range': 'Rango de Precios',
    'clear_all': 'Limpiar Todo',
    'shopping_cart': 'Carrito de Compras',
    'wishlist': 'Lista de Deseos',
    'empty_cart': 'Tu carrito está vacío',
    'empty_wishlist': 'Tu lista de deseos está vacía',
    'add_all_to_cart': 'Agregar Todo',
    'my_cart': 'Mi Carrito',
    'total': 'Total:',
    'start_shopping': 'Comprar',
    'your_cart_is_empty': 'Carrito vacio',
    'hot': 'Popular',
    'favorites': 'Favoritos',
    'saved_items': 'articulos',
    'all_items_in_stock': 'En stock',
    'move_all_to_cart': 'Al Carrito',
    'no_items_to_move': 'Nada',
    'moved_all_to_cart': 'Movido!',
    'account_profile': 'Cuenta',
    'orders': 'Pedidos',
    'vouchers': 'Cupones',
    'personal_info': 'Info Personal',
    'personal_info_desc': 'Nombre, Correo, Tel',
    'my_orders_desc': 'Historial',
    'promos_alerts': 'Promos',
    'payment_methods': 'Metodos de Pago',
    'payment_methods_desc': 'Visa 4242',
    'faq_desc': 'Soporte',
    'sign_out_desc': 'Cerrar sesion',
    'pending': 'Pendiente',
    'track': 'Rastrear',
    'details': 'Detalles',
    'no_orders_yet': 'Sin pedidos.',
    'main_collections': 'COLECCIONES',
    'choose_a_category': 'Elige Categoría',
    'popular_caps': 'POPULAR',
    'items_count': ' articulos',
    'top_customer_review': 'MEJOR RESEÑA',
    'verified_buyer': 'Comprador',
    'description_caps': 'DESCRIPCIÓN',
    'size_guide': 'Guia de Tallas',
    'select_size': 'SELECCIONAR TALLA',
    'quantity': 'Cantidad',
    'default': 'Predeterminado',
  },
  'ZH (CN)': {
    'home': '??',
    'cart': '???',
    'favorite': '??',
    'profile': '??',
    'search_hint': '???????...',
    'popular_deals': '????',
    'see_all': '????',
    'new_arrivals': '????',
    'categories': '??',
    'my_orders': '????',
    'settings': '??',
    'notifications': '??',
    'help_support': '?????',
    'logout': '????',
    'checkout': '??',
    'subtotal': '??',
    'shipping': '??',
    'place_order': '????',
    'add_to_cart': '?????',
    'buy_now': '????',
    'size': '??',
    'color': '??',
    'description': '??',
    'reviews': '??',
    'filter': '??',
    'apply_filter': '????',
    'price_range': '????',
    'clear_all': '????',
    'shopping_cart': '???',
    'wishlist': '???',
    'empty_cart': '????????',
    'empty_wishlist': '????????',
    'add_all_to_cart': '???????',
    'my_cart': '?????',
    'total': '??:',
    'start_shopping': '????',
    'your_cart_is_empty': '????',
    'hot': '??',
    'favorites': '???',
    'saved_items': '?',
    'all_items_in_stock': '????',
    'move_all_to_cart': '?????',
    'no_items_to_move': '????',
    'moved_all_to_cart': '??????!',
    'account_profile': '??',
    'orders': '??',
    'vouchers': '???',
    'personal_info': '????',
    'personal_info_desc': '??, ??, ??',
    'my_orders_desc': '????',
    'promos_alerts': '??',
    'payment_methods': '????',
    'payment_methods_desc': 'Visa 4242',
    'faq_desc': '??',
    'sign_out_desc': '??',
    'pending': '???',
    'track': '??',
    'details': '??',
    'no_orders_yet': '?????',
    'main_collections': '????',
    'choose_a_category': '????',
    'popular_caps': '??',
    'items_count': ' ???',
    'top_customer_review': '????',
    'verified_buyer': '?????',
    'description_caps': '????',
    'size_guide': '????',
    'select_size': '????',
    'quantity': '??',
    'default': '??',
  },
};

String tr(String key) {
  final lang = globalLanguage.value;
  if (dictionary.containsKey(lang) && dictionary[lang]!.containsKey(key)) {
    return dictionary[lang]![key]!;
  }
  return dictionary['EN (US)']?[key] ?? key;
}
"""

with codecs.open('lib/core/localization.dart', 'w', 'utf-8') as f:
    f.write(content)

print("localization.dart fully rewritten")
