import 'package:flutter/material.dart';

final ValueNotifier<String> globalLanguage = ValueNotifier('EN (US)');

const Map<String, Map<String, String>> dictionary = {
  'EN (US)': {
    'home': 'Home',
    'cart': 'Cart',
    'favorite': 'Favorite',
    'profile': 'Profile',
    'search_hint': 'Search clothes, collections...',
    'popular_deals': 'Popular Deals',
    'see_all': 'See All',
    'new_arrivals': 'New Arrivals',
    'categories': 'Categories',
    'my_orders': 'My Orders',
    'settings': 'Settings',
    'notifications': 'Notifications',
    'help_support': 'Help & Support',
    'logout': 'Logout',
    'checkout': 'Checkout',
    'subtotal': 'Subtotal',
    'shipping': 'Shipping',
    'place_order': 'Place Order',
    'add_to_cart': 'Add to Cart',
    'buy_now': 'Buy Now',
    'size': 'Size',
    'color': 'Color',
    'description': 'Description',
    'reviews': 'Reviews',
    'filter': 'Filter',
    'apply_filter': 'Apply Filter',
    'price_range': 'Price Range',
    'clear_all': 'Clear All',
    'shopping_cart': 'Shopping Cart',
    'wishlist': 'Wishlist',
    'empty_cart': 'Your cart is empty',
    'empty_wishlist': 'Your wishlist is empty',
    'add_all_to_cart': 'Add All to Cart',
    'my_cart': 'My Cart',
    'total': 'Total:',
    'start_shopping': 'Start Shopping',
    'your_cart_is_empty': 'Your Cart is Empty',
    'hot': 'Hot',
    'favorites': 'Favorites',
    'saved_items': 'saved items',
    'all_items_in_stock': 'All items in stock',
    'move_all_to_cart': 'Move All to Cart',
    'no_items_to_move': 'No items to move',
    'moved_all_to_cart': 'Moved all to Cart!',
    'account_profile': 'Account & Profile',
    'orders': 'Orders',
    'vouchers': 'Vouchers',
    'personal_info': 'Personal Info',
    'personal_info_desc': 'Name, Email, Phone number',
    'my_orders_desc': 'Order history & tracking',
    'promos_alerts': 'Promos & status alerts',
    'payment_methods': 'Payment Methods',
    'payment_methods_desc': 'Visa ending in 4242',
    'faq_desc': 'FAQ & Customer Service',
    'sign_out_desc': 'Sign out of your account',
    'pending': 'Pending',
    'track': 'Track',
    'details': 'Details',
    'no_orders_yet': 'No orders yet.',
    'main_collections': 'MAIN COLLECTIONS',
    'choose_a_category': 'Choose a Category',
    'popular_caps': 'POPULAR',
    'items_count': ' items',
    'top_customer_review': 'TOP CUSTOMER REVIEW',
    'verified_buyer': 'Verified Buyer',
    'description_caps': 'DESCRIPTION',
    'size_guide': 'Size Guide',
    'select_size': 'SELECT SIZE',
    'quantity': 'Quantity',
    'default': 'Default',
    'welcome_back': 'Welcome Back',
    'sign_in_desc': 'Sign in to continue exploring top fashion & deals',
    'email_phone': 'Email or Phone Number',
    'password': 'Password',
    'remember_me': 'Remember me',
    'forgot_password': 'Forgot Password?',
    'log_in': 'Log In',
    'or_continue_with': 'OR CONTINUE WITH',
    'dont_have_account': "Don't have an account? ",
    'sign_up': 'Sign up',
    'secure_encryption': '256-bit Secure Encryption  Protected by Cescrafli',
    'please_fill_all': 'Please fill all fields',
    'login_failed': 'Login failed. Check credentials.',
    'create_account': 'Create Account',
    'join_desc': 'Join Cescrafli to unlock exclusive deals and personalized fashion.',
    'full_name': 'Full Name',
    'email_address': 'Email Address',
    'phone_number': 'Phone Number',
    'terms_privacy': 'Terms & Privacy Policy',
    'already_have_account': 'Already have an account? ',
    'recent_searches': 'Recent Searches',
    'trending_now': 'Trending Now',
    'promos_deals': 'Promos & Deals',
    'account': 'Account',
    'today': 'TODAY',
    'earlier_this_week': 'EARLIER THIS WEEK',
    'mark_group_read': 'Mark group read',
    'track_order': 'Track Order',
    'shop_deals': 'Shop Deals',
    'no_notifications': 'No notifications',
    'help_support_title': 'Help & Support',
    'browse_categories': 'Browse categories',
    'how_can_we_help': 'How can we help you?',
    'explore_faq': 'Explore FAQ',
    'orders_shipping': 'Orders & Shipping',
    'payments_refunds': 'Payments & Refunds',
    'my_support_ticket': 'MY SUPPORT TICKET',
    'in_progress': 'In Progress',

  },
  'ID (ID)': {
    'home': 'Beranda',
    'cart': 'Keranjang',
    'favorite': 'Favorit',
    'profile': 'Profil',
    'search_hint': 'Cari pakaian, koleksi...',
    'popular_deals': 'Promo Populer',
    'see_all': 'Lihat Semua',
    'new_arrivals': 'Produk Baru',
    'categories': 'Kategori',
    'my_orders': 'Pesanan Saya',
    'settings': 'Pengaturan',
    'notifications': 'Notifikasi',
    'help_support': 'Bantuan & Dukungan',
    'logout': 'Keluar',
    'checkout': 'Pembayaran',
    'subtotal': 'Subtotal',
    'shipping': 'Pengiriman',
    'place_order': 'Buat Pesanan',
    'add_to_cart': 'Ke Keranjang',
    'buy_now': 'Beli Sekarang',
    'size': 'Ukuran',
    'color': 'Warna',
    'description': 'Deskripsi',
    'reviews': 'Ulasan',
    'filter': 'Penyaring',
    'apply_filter': 'Terapkan Filter',
    'price_range': 'Rentang Harga',
    'clear_all': 'Hapus Semua',
    'shopping_cart': 'Keranjang Belanja',
    'wishlist': 'Daftar Keinginan',
    'empty_cart': 'Keranjang Anda kosong',
    'empty_wishlist': 'Wishlist Anda kosong',
    'add_all_to_cart': 'Masukkan Semua',
    'my_cart': 'Keranjang Saya',
    'total': 'Total:',
    'start_shopping': 'Mulai Belanja',
    'your_cart_is_empty': 'Keranjang Kosong',
    'hot': 'Populer',
    'favorites': 'Favorit',
    'saved_items': 'disimpan',
    'all_items_in_stock': 'Semua tersedia',
    'move_all_to_cart': 'Pindah ke Keranjang',
    'no_items_to_move': 'Tidak ada',
    'moved_all_to_cart': 'Berhasil dipindah!',
    'account_profile': 'Akun & Profil',
    'orders': 'Pesanan',
    'vouchers': 'Voucher',
    'personal_info': 'Info Pribadi',
    'personal_info_desc': 'Nama, Email, No HP',
    'my_orders_desc': 'Riwayat pesanan',
    'promos_alerts': 'Promo & notifikasi',
    'payment_methods': 'Metode Pembayaran',
    'payment_methods_desc': 'Visa berakhiran 4242',
    'faq_desc': 'FAQ & Bantuan',
    'sign_out_desc': 'Keluar dari akun',
    'pending': 'Menunggu',
    'track': 'Lacak',
    'details': 'Detail',
    'no_orders_yet': 'Belum ada pesanan.',
    'main_collections': 'KOLEKSI UTAMA',
    'choose_a_category': 'Pilih Kategori',
    'popular_caps': 'POPULER',
    'items_count': ' barang',
    'top_customer_review': 'ULASAN TERBAIK',
    'verified_buyer': 'Pembeli Terverifikasi',
    'description_caps': 'DESKRIPSI',
    'size_guide': 'Panduan Ukuran',
    'select_size': 'PILIH UKURAN',
    'quantity': 'Kuantitas',
    'default': 'Bawaan',
    'welcome_back': 'Selamat Datang',
    'sign_in_desc': 'Masuk untuk menjelajahi fashion terbaik',
    'email_phone': 'Email atau No. Telepon',
    'password': 'Kata Sandi',
    'remember_me': 'Ingat saya',
    'forgot_password': 'Lupa Kata Sandi?',
    'log_in': 'Masuk',
    'or_continue_with': 'ATAU MASUK DENGAN',
    'dont_have_account': 'Belum punya akun? ',
    'sign_up': 'Daftar',
    'secure_encryption': 'Enkripsi Aman 256-bit',
    'please_fill_all': 'Mohon isi semua bidang',
    'login_failed': 'Gagal masuk. Periksa kredensial.',
    'create_account': 'Buat Akun',
    'join_desc': 'Gabung Cescrafli untuk penawaran eksklusif.',
    'full_name': 'Nama Lengkap',
    'email_address': 'Alamat Email',
    'phone_number': 'Nomor Telepon',
    'terms_privacy': 'Syarat & Kebijakan Privasi',
    'already_have_account': 'Sudah punya akun? ',
    'recent_searches': 'Pencarian Terbaru',
    'trending_now': 'Trending Sekarang',
    'promos_deals': 'Promo & Penawaran',
    'account': 'Akun',
    'today': 'HARI INI',
    'earlier_this_week': 'MINGGU INI',
    'mark_group_read': 'Tandai sudah dibaca',
    'track_order': 'Lacak Pesanan',
    'shop_deals': 'Beli Promo',
    'no_notifications': 'Tidak ada notifikasi',
    'help_support_title': 'Bantuan & Dukungan',
    'browse_categories': 'Telusuri kategori',
    'how_can_we_help': 'Apa yang bisa kami bantu?',
    'explore_faq': 'Jelajahi FAQ',
    'orders_shipping': 'Pesanan & Pengiriman',
    'payments_refunds': 'Pembayaran & Pengembalian',
    'my_support_ticket': 'TIKET SAYA',
    'in_progress': 'Dalam Proses',

  },
  'ES (ES)': {
    'home': 'Inicio',
    'cart': 'Carrito',
    'favorite': 'Favorito',
    'profile': 'Perfil',
    'search_hint': 'Buscar ropa, colecciones...',
    'popular_deals': 'Ofertas Populares',
    'see_all': 'Ver Todo',
    'new_arrivals': 'Nuevas Llegadas',
    'categories': 'Categorías',
    'my_orders': 'Mis Pedidos',
    'settings': 'Configuración',
    'notifications': 'Notificaciones',
    'help_support': 'Ayuda y Soporte',
    'logout': 'Cerrar Sesión',
    'checkout': 'Pagar',
    'subtotal': 'Subtotal',
    'shipping': 'Envío',
    'place_order': 'Hacer Pedido',
    'add_to_cart': 'Al Carrito',
    'buy_now': 'Comprar Ahora',
    'size': 'Tamaño',
    'color': 'Color',
    'description': 'Descripción',
    'reviews': 'Reseñas',
    'filter': 'Filtrar',
    'apply_filter': 'Aplicar Filtro',
    'price_range': 'Rango de Precios',
    'clear_all': 'Limpiar Todo',
    'shopping_cart': 'Carrito de Compras',
    'wishlist': 'Lista de Deseos',
    'empty_cart': 'Tu carrito está vacío',
    'empty_wishlist': 'Tu lista de deseos está vacía',
    'add_all_to_cart': 'Agregar Todo',
    'my_cart': 'Mi Carrito',
    'total': 'Total:',
    'start_shopping': 'Comprar',
    'your_cart_is_empty': 'Carrito vacio',
    'hot': 'Popular',
    'favorites': 'Favoritos',
    'saved_items': 'articulos',
    'all_items_in_stock': 'En stock',
    'move_all_to_cart': 'Al Carrito',
    'no_items_to_move': 'Nada',
    'moved_all_to_cart': 'Movido!',
    'account_profile': 'Cuenta',
    'orders': 'Pedidos',
    'vouchers': 'Cupones',
    'personal_info': 'Info Personal',
    'personal_info_desc': 'Nombre, Correo, Tel',
    'my_orders_desc': 'Historial',
    'promos_alerts': 'Promos',
    'payment_methods': 'Metodos de Pago',
    'payment_methods_desc': 'Visa 4242',
    'faq_desc': 'Soporte',
    'sign_out_desc': 'Cerrar sesion',
    'pending': 'Pendiente',
    'track': 'Rastrear',
    'details': 'Detalles',
    'no_orders_yet': 'Sin pedidos.',
    'main_collections': 'COLECCIONES',
    'choose_a_category': 'Elige Categoría',
    'popular_caps': 'POPULAR',
    'items_count': ' articulos',
    'top_customer_review': 'MEJOR RESEÑA',
    'verified_buyer': 'Comprador',
    'description_caps': 'DESCRIPCIÓN',
    'size_guide': 'Guia de Tallas',
    'select_size': 'SELECCIONAR TALLA',
    'quantity': 'Cantidad',
    'default': 'Predeterminado',
    'welcome_back': 'Bienvenido',
    'sign_in_desc': 'Inicie sesion para explorar la mejor moda',
    'email_phone': 'Correo o Telefono',
    'password': 'Contrasena',
    'remember_me': 'Recuerdame',
    'forgot_password': 'Olvido su contrasena?',
    'log_in': 'Iniciar Sesion',
    'or_continue_with': 'O CONTINUAR CON',
    'dont_have_account': 'No tiene cuenta? ',
    'sign_up': 'Registrarse',
    'secure_encryption': 'Cifrado seguro de 256 bits',
    'please_fill_all': 'Complete todos los campos',
    'login_failed': 'Error al iniciar sesion.',
    'create_account': 'Crear Cuenta',
    'join_desc': 'Unete a Cescrafli para ofertas exclusivas.',
    'full_name': 'Nombre Completo',
    'email_address': 'Correo Electronico',
    'phone_number': 'Numero de Telefono',
    'terms_privacy': 'Terminos y Privacidad',
    'already_have_account': 'Ya tiene cuenta? ',
    'recent_searches': 'Busquedas recientes',
    'trending_now': 'Tendencias',
    'promos_deals': 'Promos y Ofertas',
    'account': 'Cuenta',
    'today': 'HOY',
    'earlier_this_week': 'ESTA SEMANA',
    'mark_group_read': 'Marcar como leido',
    'track_order': 'Rastrear pedido',
    'shop_deals': 'Ver Ofertas',
    'no_notifications': 'Sin notificaciones',
    'help_support_title': 'Ayuda y Soporte',
    'browse_categories': 'Explorar categorias',
    'how_can_we_help': 'Como podemos ayudarte?',
    'explore_faq': 'Explorar FAQ',
    'orders_shipping': 'Pedidos y Envios',
    'payments_refunds': 'Pagos y Devoluciones',
    'my_support_ticket': 'MI TICKET',
    'in_progress': 'En Progreso',

  },
  'ZH (CN)': {
    'home': '首页',
    'cart': '购物车',
    'favorite': '收藏',
    'profile': '我的',
    'search_hint': '搜索衣服、系列...',
    'popular_deals': '热门优惠',
    'see_all': '查看全部',
    'new_arrivals': '新品上市',
    'categories': '分类',
    'my_orders': '我的订单',
    'settings': '设置',
    'notifications': '通知',
    'help_support': '帮助与支持',
    'logout': '退出登录',
    'checkout': '结账',
    'subtotal': '小计',
    'shipping': '运费',
    'place_order': '提交订单',
    'add_to_cart': '加入购物车',
    'buy_now': '立即购买',
    'size': '尺码',
    'color': '颜色',
    'description': '描述',
    'reviews': '评价',
    'filter': '筛选',
    'apply_filter': '应用筛选',
    'price_range': '价格范围',
    'clear_all': '清除全部',
    'shopping_cart': '购物车',
    'wishlist': '心愿单',
    'empty_cart': '您的购物车是空的',
    'empty_wishlist': '您的心愿单是空的',
    'add_all_to_cart': '全部加入购物车',
    'my_cart': '我的购物车',
    'total': '总计:',
    'start_shopping': '开始购物',
    'your_cart_is_empty': '购物车空',
    'hot': '热门',
    'favorites': '收藏夹',
    'saved_items': '件',
    'all_items_in_stock': '全部有货',
    'move_all_to_cart': '移至购物车',
    'no_items_to_move': '没有商品',
    'moved_all_to_cart': '已移至购物车!',
    'account_profile': '账户',
    'orders': '订单',
    'vouchers': '代金券',
    'personal_info': '个人信息',
    'personal_info_desc': '姓名, 邮箱, 电话',
    'my_orders_desc': '历史订单',
    'promos_alerts': '提醒',
    'payment_methods': '支付方式',
    'payment_methods_desc': 'Visa 4242',
    'faq_desc': '客服',
    'sign_out_desc': '退出',
    'pending': '待处理',
    'track': '追踪',
    'details': '详情',
    'no_orders_yet': '暂无订单。',
    'main_collections': '主要系列',
    'choose_a_category': '选择分类',
    'popular_caps': '热门',
    'items_count': ' 件商品',
    'top_customer_review': '精选评价',
    'verified_buyer': '已验证买家',
    'description_caps': '商品描述',
    'size_guide': '尺码指南',
    'select_size': '选择尺码',
    'quantity': '数量',
    'default': '默认',
    'welcome_back': '欢迎回来',
    'sign_in_desc': '请输入您的邮箱和密码',
    'email_phone': '电子邮箱',
    'password': '密码',
    'remember_me': '记住我',
    'forgot_password': '忘记密码？',
    'log_in': '登录',
    'or_continue_with': '或使用以下方式继续',
    'dont_have_account': '还没有账号？',
    'sign_up': '注册',
    'secure_encryption': '256位安全加密',
    'please_fill_all': '请填写所有字段',
    'login_failed': '登录失败，请重试',
    'create_account': '创建账号',
    'join_desc': '加入Cescrafli并享受独家优惠',
    'full_name': '全名',
    'email_address': '电子邮件',
    'phone_number': '手机号码',
    'terms_privacy': '同意服务条款和隐私政策',
    'already_have_account': '已有账号？ ',
    'recent_searches': '最近搜索',
    'trending_now': '今日热门',
    'promos_deals': '优惠和折扣',
    'account': '账号',
    'today': '今天',
    'earlier_this_week': '本周早些时候',
    'mark_group_read': '将此组标记为已读',
    'track_order': '跟踪订单',
    'shop_deals': '选购优惠',
    'no_notifications': '暂无通知',
    'help_support_title': '帮助与支持',
    'browse_categories': '浏览分类',
    'how_can_we_help': '我们能帮您什么？',
    'explore_faq': '浏览常见问题',
    'orders_shipping': '订单与配送',
    'payments_refunds': '付款与退款',
    'my_support_ticket': '我的支持工单',
    'in_progress': '处理中',

  },
};

String tr(String key) {
  final lang = globalLanguage.value;
  if (dictionary.containsKey(lang) && dictionary[lang]!.containsKey(key)) {
    return dictionary[lang]![key]!;
  }
  return dictionary['EN (US)']?[key] ?? key;
}
